sonar.organization=yassinelc
sonar.projectKey=YassineLC_book-catalogue-devops
sonar.projectName=Book Catalogue DevOps
sonar.projectVersion=1.0
sonar.host.url=https://sonarcloud.io

sonar.sources=backend/book-service/src/main/java,backend/author-service/src/main/java
sonar.tests=backend/book-service/src/test/java,backend/author-service/src/test/java
sonar.java.binaries=backend/book-service/build/classes/java/main,backend/author-service/build/classes/java/main
sonar.coverage.jacoco.xmlReportPaths=backend/book-service/build/reports/jacoco/test/jacocoTestReport.xml,backend/author-service/build/reports/jacoco/test/jacocoTestReport.xml
sonar.exclusions=frontend/**
