sonar.organization=yassinelc
sonar.projectKey=yassinelc_book-catalogue-devops
sonar.projectName=Book Catalogue DevOps
sonar.projectVersion=1.0
sonar.host.url=https://sonarcloud.io

sonar.modules=book-service,author-service

book-service.sonar.projectName=Book Service
book-service.sonar.projectBaseDir=backend/book-service
book-service.sonar.sources=src/main/java
book-service.sonar.tests=src/test/java
book-service.sonar.java.binaries=build/classes/java/main
book-service.sonar.coverage.jacoco.xmlReportPaths=build/reports/jacoco/test/jacocoTestReport.xml

author-service.sonar.projectName=Author Service
author-service.sonar.projectBaseDir=backend/author-service
author-service.sonar.sources=src/main/java
author-service.sonar.tests=src/test/java
author-service.sonar.java.binaries=build/classes/java/main
author-service.sonar.coverage.jacoco.xmlReportPaths=build/reports/jacoco/test/jacocoTestReport.xml
